musicApp/albums/urls.py
from django.urls import path, include
from albums import views

urlpatterns = [
    path("add/", views.AlbumCreateView.as_view(), name='add-album'),
    path('<int:id>/', include([
        path('edit/', views.AlbumEditView.as_view(), name='album-edit'),
        path('details/', views.AlbumDetailsView.as_view(), name='album-details'),
        path('delete/', views.AlbumDeleteView.as_view(), name='album-delete'),
    ]))
]

musicApp/common/urls.py
from django.urls import path
from common.views import HomePage

urlpatterns = [
    path('', HomePage.as_view(), name='home')
]

musicApp/musicApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('album/', include('albums.urls')),
    path('profile/', include('profiles.urls')),
]

musicApp/profiles/urls.py
from django.urls import path
from profiles import views

urlpatterns = [
    path("details/", views.ProfileDetailView.as_view(), name='profile-details'),
    path("delete/", views.ProfileDeleteView.as_view(), name='profile-delete'),
]

musicApp/albums/models.py
from django.db import models
from albums.choices import GenreChoices
from django.core.validators import MinValueValidator

class Album(models.Model):
    album_name = models.CharField(
        max_length = 30,
        unique = True,
        )

    artist = models.CharField(
        max_length = 30,
        )
    
    genre = models.CharField(
        max_length = 50,
        choices=GenreChoices.choices,
        )

    description = models.TextField(
        blank = True,
        null = True,
    )

    image_url = models.URLField()

    price = models.FloatField(
        validators=[
            MinValueValidator(0.0),
        ]
    )

    owner = models.ForeignKey(
        to = 'profiles.Profile',
        related_name = "albums",
        on_delete = models.CASCADE,
    )

musicApp/common/models.py
from django.db import models

# Create your models here.

musicApp/profiles/models.py
from django.db import models
from django.core.validators import MinLengthValidator

from profiles.validators import AlphaNumericValidator

class Profile(models.Model):

    username = models.CharField(
            max_length=15,
            validators=[
                MinLengthValidator(2),
                AlphaNumericValidator(),
            ]
        )
    
    email = models.EmailField()

    age = models.PositiveIntegerField(
        blank = True,
        null = True, 
    )

musicApp/albums/forms.py
from django import forms
from albums.models import Album
from musicApp.mixins import PlaceholderMixin, ReadOnlyMixin


class AlbumBaseForm(forms.ModelForm):
    class Meta:
        model = Album
        exclude = ('owner', )

class AlbumCreateForm(PlaceholderMixin, AlbumBaseForm):
    pass


class AlbumEditForm(PlaceholderMixin, AlbumBaseForm):
    pass

class AlbumDeleteForm(ReadOnlyMixin, AlbumBaseForm):
    read_only_fields = ['image_url', 'album_name', 'artist', 'genre', 'price', 'description']

musicApp/profiles/forms.py
from django import forms
from profiles.models import Profile

class ProfileBaseForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = "__all__"

class ProfileCreateForm(ProfileBaseForm):
    pass

musicApp/albums/views.py
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView
from albums.models import Album
from albums.forms import AlbumCreateForm, AlbumEditForm, AlbumDeleteForm
from musicApp.utils import get_user_obj
from django.urls import reverse_lazy


class AlbumCreateView(CreateView):
    model = Album
    form_class = AlbumCreateForm
    template_name = 'albums/album-add.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.owner = get_user_obj()
        return super().form_valid(form)
    

class AlbumEditView(UpdateView):
    model = Album
    form_class = AlbumEditForm
    pk_url_kwarg = 'id'
    template_name = 'albums/album-edit.html'
    success_url = reverse_lazy('home')

class AlbumDeleteView(DeleteView):
    model = Album
    form_class = AlbumDeleteForm
    pk_url_kwarg = 'id'
    template_name = 'albums/album-delete.html'
    success_url = reverse_lazy('home')

    def get_initial(self):
        return self.object.__dict__

    def form_invalid(self, form):
        return self.form_valid(form)

class AlbumDetailsView(DetailView):
    model = Album
    pk_url_kwarg = 'id'
    template_name = 'albums/album-details.html'

musicApp/common/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import BaseFormView
from musicApp.utils import get_user_obj
from albums.models import Album
from profiles.forms import ProfileCreateForm


class HomePage(ListView, BaseFormView):
    model = Album
    form_class = ProfileCreateForm
    success_url = reverse_lazy('home')    

    def get_template_names(self):
        prfile = get_user_obj()

        if prfile:
            return ['profiles/home-with-profile.html']

        return ['profiles/home-no-profile.html']

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
        
    

musicApp/profiles/views.py
from django.views.generic import DetailView, DeleteView
from profiles.models import Profile
from musicApp.utils import get_user_obj
from django.urls import reverse_lazy

class ProfileDetailView(DetailView):
    template_name = 'profiles/profile-details.html'

    def get_object(self, queryset=None):
        return get_user_obj()

class ProfileDeleteView(DeleteView):
    template_name = 'profiles/profile-delete.html'
    success_url = reverse_lazy('home')

    def get_object(self, queryset=None):
        return get_user_obj()

musicApp/templates/albums/album-add.html
{% extends "base.html" %} 
{% block content %}
<section class="createPage">
  <form method="post">
    <fieldset>
      <legend>Add Album</legend>
      <div class="container">
        {% csrf_token %}
        {{ form }}
        <button class="add-album" type="submit">Add New Album</button>
      </div>
    </fieldset>
  </form>
</section>
{% endblock %}

musicApp/templates/albums/album-delete.html
{% extends "base.html" %} 
{% block content %}
<section class="editPage">
  <form method='post'>
    <fieldset>
      <legend>Delete Album</legend>
      <div class="container">
        {% csrf_token %}
        {{form}}
        <button class="delete-album" type="submit">Delete Album</button>
      </div>
    </fieldset>
  </form>
</section>

{% endblock %}

musicApp/templates/albums/album-details.html
{% extends "base.html" %} 
{% block content %}
<section id="detailsPage">
  <div class="wrapper">
    <div class="albumCover">
      <img src="{{album.image_url}}" alt="Cover Image" />
    </div>

    <div class="albumInfo">
      <div class="albumText">
        <h1>Name: {{album.album_name}}</h1>
        <h3>Artist: {{album.artist}}</h3>
        <h4>Genre: {{album.genre}}</h4>
        <h4>Price: {{album.price|floatformat:2}}</h4>
        {% if album.description %}
          <p>
            Description: {{album.description}}
          </p>
        {% endif %}
      </div>

      <div class="actionBtn">
        <a href="{% url 'album-edit' album.pk %}" class="edit">Edit</a>
        <a href="{% url "album-delete" album.pk %}" class="remove">Delete</a>
      </div>
    </div>
  </div>
</section>
{% endblock %}

musicApp/templates/albums/album-edit.html
{% extends "base.html" %}
{% block content %}
<section class="editPage">
  <form method='post'>
    <fieldset>
      <legend>Edit Album</legend>
      <div class="container">
        {% csrf_token %}
        {{form}}

        <button class="edit-album" type="submit">Edit Album</button>
      </div>
    </fieldset>
  </form>
</section>
{% endblock %}

musicApp/templates/base.html
{% load static %}
{% load get_user %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>My Music App</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}" />
  </head>

  <body>
    <div id="box">
      <header>
        <nav>
          <img src="{% static "images/headphones.png" %}" alt="headphones" />
          <a href="{% url "home" %}">Home</a>
          <ul></ul>
          {% get_user as profile %}
          {% if  profile %}
          <ul>
            <li><a href="{% url "add-album" %}">Create Album</a></li>
            <li><a href="{% url "profile-details" %}">Profile</a></li>
          </ul>
          {% endif %}
          
        </nav>
      </header>
      {% block content %}
      {% endblock%}
      <footer>
        <div>&copy;SoftUni Team 2024. All rights reserved.</div>
      </footer>
    </div>
  </body>
</html>

musicApp/templates/profiles/home-no-profile.html
{% extends "base.html" %} 
{% load static %}
{% block content %}
<div class="container-inline">
  <section id="welcomePage">
    <div id="welcome-message">
      <h1>Welcome to</h1>
      <h1>My Music App!</h1>
    </div>
    <div class="music-img">
      <img src="{% static '/images/musicIcons.webp' %}" alt="music-icon" />
    </div>
  </section>

  <section id="registerPage">
    <form method="post">
      <fieldset>
        <legend>Profile</legend>
        {% csrf_token %}
        {{form}}
        <button type="submit" class="register">Enter</button>
      </fieldset>
    </form>
  </section>
</div>
{% endblock %}

musicApp/templates/profiles/home-with-profile.html
{% extends "base.html" %} {% block content %}

<section id="catalogPage">

  {% if album_list %}
  <h1>All Albums</h1>
  {% else %}
  <p>No Albums in Catalog!</p>
  {% endif %}

  {% for album in album_list %}
  <div class="card-box">
    <img src="{{album.image_url}}" alt="Cover Image" />
    <div>
      <div class="text-center">
        <p class="name">Name: {{album.album_name}}</p>
        <p class="artist">Artist: {{album.artist}}</p>
        <p class="genre">Genre: {{album.genre}}</p>
        <p class="price">Price: {{album.price|floatformat:2}}</p>
      </div>
      <div class="btn-group">
        <a href="{% url "album-details" album.pk %}">Details</a>
      </div>
    </div>
  </div>
  {% endfor %}

</section>

{% endblock %}

musicApp/templates/profiles/profile-delete.html
{% extends "base.html" %} 
{% block content %}
<section id="detailsPage">
  <div class="wrapper">
    <div class="profileText">
      <h1>Are you sure you want to delete your profile?</h1>
      <form method='post'>
        {% csrf_token %}
        <button class="delete-profile" type="submit">Delete</button>
      </form>
    </div>
  </div>
</section>
{% endblock %}

musicApp/templates/profiles/profile-details.html
{% extends "base.html" %} 
{% block content %}
<section id="detailsPage">
  <div class="wrapper">
    <div class="profilePage">
      <img
        src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png"
        alt="Profile Image"
      />
    </div>

    <div class="profileText">
      <h1>Username: {{object.username}}</h1>
      <h1>Email: {{object.email}}</h1>
      <h1>Age: {{object.age}}</h1>
      <h1>Albums: {{object.albums.count}}</h1>
    </div>

    <div class="actionBtn">
      <a href="{% url "profile-delete" %}" class="remove">Delete</a>
    </div>
  </div>
</section>
{% endblock %}